# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src/reflect
src/generic
src
src/headers
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_Foundation-import-private.h
src/reflect/_Foundation-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/generic/import-private.h
src/generic/include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_Foundation-export.h
src/reflect/_Foundation-import.h
src/reflect/_Foundation-include.h
src/reflect/_Foundation-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/generic/import.h
src/generic/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/Foundation.h
src/NSDebug.h
src/NSMutableCopying.h
src/NSObjCRuntime.h
src/headers/NSArchiver.h
src/headers/NSArray.h
src/headers/NSAutoreleasePool.h
src/headers/NSBundle.h
src/headers/NSByteOrder.h
src/headers/NSCalendarDate.h
src/headers/NSCalendar.h
src/headers/NSCharacterSet.h
src/headers/NSCoder.h
src/headers/NSData.h
src/headers/NSDateFormatter.h
src/headers/NSDate.h
src/headers/NSDecimalNumber.h
src/headers/NSDecimal.h
src/headers/NSDictionary.h
src/headers/NSEnumerator.h
src/headers/NSError.h
src/headers/NSException.h
src/headers/NSFileHandle.h
src/headers/NSFileManager.h
src/headers/NSFormatter.h
src/headers/NSHost.h
src/headers/NSLocale.h
src/headers/NSLock.h
src/headers/NSMutableArray.h
src/headers/NSMutableCharacterSet.h
src/headers/NSMutableData.h
src/headers/NSMutableDictionary.h
src/headers/NSMutableSet.h
src/headers/NSMutableString.h
src/headers/NSNotificationCenter.h
src/headers/NSNotification.h
src/headers/NSNull.h
src/headers/NSNumberFormatter.h
src/headers/NSNumber.h
src/headers/NSObject.h
src/headers/NSPathUtilities.h
src/headers/NSProcessInfo.h
src/headers/NSProxy.h
src/headers/NSRange.h
src/headers/NSRunLoop.h
src/headers/NSScanner.h
src/headers/NSSet.h
src/headers/NSString.h
src/headers/NSTask.h
src/headers/NSThread.h
src/headers/NSTimeZone.h
src/headers/NSTimer.h
src/headers/NSURL.h
src/headers/NSUndoManager.h
src/headers/NSUserDefaults.h
src/headers/NSValue.h
src/headers/NSZone.h
)

