#ifndef foundation_import_h__
#define foundation_import_h__

/* This is a central include file to keep dependencies out of the library
   Objective-C files. It is usally imported by Objective-C .h files only.
   .m and .aam use import-private.h.
*/


/* need this here, because include.h is in the back */

#ifndef FOUNDATION_GLOBAL

#ifdef FOUNDATION_BUILD
# define FOUNDATION_GLOBAL    MULLE_C_GLOBAL
#else
# if defined( FOUNDATION_INCLUDE_DYNAMIC) || (defined( MULLE_INCLUDE_DYNAMIC) && ! defined( FOUNDATION_INCLUDE_STATIC))
#  define FOUNDATION_GLOBAL   MULLE_C_EXTERN_GLOBAL
# else
#  define FOUNDATION_GLOBAL   extern
# endif
#endif

#endif

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#import "_Foundation-import.h"


/* You can add some more import statements here */

/*
   Get C includes last in this library
 */
#include "include.h"

#endif
