/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _Foundation_include_h__
#define _Foundation_include_h__

// How to tweak the following mulle-objc-compat #include
//    remove:             `mulle-sourcetree mark mulle-objc-compat no-header`
//    rename:             `mulle-sde dependency|library set mulle-objc-compat include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-objc-compat [no-]import`
//    toggle localheader: `mulle-sourcetree mark mulle-objc-compat [no-]localheader`
//    toggle public:      `mulle-sourcetree mark mulle-objc-compat [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-objc-compat [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-objc-compat no-os-<osname>`
# if defined( __has_include) && __has_include("mulle-objc-compat.h")
#   include "mulle-objc-compat.h"   // mulle-objc-compat
# else
#   include <mulle-objc-compat/mulle-objc-compat.h>   // mulle-objc-compat
# endif

// How to tweak the following objc-compat #include
//    remove:             `mulle-sourcetree mark objc-compat no-header`
//    rename:             `mulle-sde dependency|library set objc-compat include whatever.h`
//    toggle #import:     `mulle-sourcetree mark objc-compat [no-]import`
//    toggle localheader: `mulle-sourcetree mark objc-compat [no-]localheader`
//    toggle public:      `mulle-sourcetree mark objc-compat [no-]public`
//    toggle optional:    `mulle-sourcetree mark objc-compat [no-]require`
//    remove for os:      `mulle-sourcetree mark objc-compat no-os-<osname>`
# if defined( __has_include) && __has_include("objc-compat.h")
#   include "objc-compat.h"   // objc-compat
# else
#   include <objc-compat/objc-compat.h>   // objc-compat
# endif

#endif
