/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _Foundation_import_h__
#define _Foundation_import_h__

// How to tweak the following MulleFoundation #import
//    remove:             `mulle-sourcetree mark MulleFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleFoundation no-os-<osname>`
# import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

// How to tweak the following MulleObjCExpatFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCExpatFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCExpatFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCExpatFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCExpatFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCExpatFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCExpatFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>)
#   import <MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>   // MulleObjCExpatFoundation
#   define HAVE_LIB_MULLE_OBJC_EXPAT_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCInetOSFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCInetOSFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCInetOSFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCInetOSFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCInetOSFoundation/MulleObjCInetOSFoundation.h>)
#   import <MulleObjCInetOSFoundation/MulleObjCInetOSFoundation.h>   // MulleObjCInetOSFoundation
#   define HAVE_LIB_MULLE_OBJC_INET_OS_FOUNDATION
#  endif
# endif

// How to tweak the following MulleObjCHTTPFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCHTTPFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCHTTPFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCHTTPFoundation no-os-<osname>`
# ifdef __has_include
#  if __has_include(<MulleObjCHTTPFoundation/MulleObjCHTTPFoundation.h>)
#   import <MulleObjCHTTPFoundation/MulleObjCHTTPFoundation.h>   // MulleObjCHTTPFoundation
#   define HAVE_LIB_MULLE_OBJC_HTTP_FOUNDATION
#  endif
# endif

#ifdef __has_include
# if __has_include( "_Foundation-include.h")
#  include "_Foundation-include.h"
# endif
#endif


#endif
