/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 445683ED-0F8E-41AA-993A-DF3A42E5813A instead of MulleFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

// You can tweak the following #import with these commands.
// (Use 3D67B37E-41CA-4A09-9BF5-F3F9A87C9592 instead of MulleObjCExpatFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCExpatFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCExpatFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCExpatFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCExpatFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCExpatFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCExpatFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCExpatFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>)
#  import <MulleObjCExpatFoundation/MulleObjCExpatFoundation.h>   // MulleObjCExpatFoundation
#  define HAVE_LIB_MULLE_OBJC_EXPAT_FOUNDATION
# endif
#endif

// You can tweak the following #import with these commands.
// (Use E5624C70-7EEE-4478-A21F-C30A91F71EC8 instead of MulleObjCInetOSFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCInetOSFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCInetOSFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCInetOSFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCInetOSFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCInetOSFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCInetOSFoundation/MulleObjCInetOSFoundation.h>)
#  import <MulleObjCInetOSFoundation/MulleObjCInetOSFoundation.h>   // MulleObjCInetOSFoundation
#  define HAVE_LIB_MULLE_OBJC_INET_OS_FOUNDATION
# endif
#endif

// You can tweak the following #import with these commands.
// (Use AE716CD1-2BDB-46E3-936B-8C33F16B71EF instead of MulleObjCHTTPFoundation if there are duplicate entries)
//    remove:             `mulle-sourcetree mark MulleObjCHTTPFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCHTTPFoundation include whatever.h`
//    reorder:            `mulle-sourcetree move MulleObjCHTTPFoundation <up|down>`
//    toggle #import:     `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCHTTPFoundation [no-]require`
//    remove for platform:`mulle-sourcetree mark MulleObjCHTTPFoundation no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#ifdef __has_include
# if __has_include(<MulleObjCHTTPFoundation/MulleObjCHTTPFoundation.h>)
#  import <MulleObjCHTTPFoundation/MulleObjCHTTPFoundation.h>   // MulleObjCHTTPFoundation
#  define HAVE_LIB_MULLE_OBJC_HTTP_FOUNDATION
# endif
#endif

#ifdef __has_include
# if __has_include( "_Foundation-include.h")
#  include "_Foundation-include.h"
# endif
#endif

