      { @selector( MulleObjCLoader), @selector( MulleFoundation) },      // 47a9beb6;MulleObjCLoader;46ed3b36;MulleFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCExpatFoundation) },      // 47a9beb6;MulleObjCLoader;e5f6fc77;MulleObjCExpatFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCHTTPFoundation) },      // 47a9beb6;MulleObjCLoader;457d3115;MulleObjCHTTPFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCInetOSFoundation) },      // 47a9beb6;MulleObjCLoader;e6af6918;MulleObjCInetOSFoundation
