/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _foundation_include_h__
#define _foundation_include_h__

// remove with `mulle-sourcetree mark mulle-objc-compat no-header`
// rename with `mulle-sourcetree mark mulle-objc-compat set include whatever.h`
# include <mulle-objc-compat/mulle-objc-compat.h>   // mulle-objc-compat

// remove with `mulle-sourcetree mark objc-compat no-header`
// rename with `mulle-sourcetree mark objc-compat set include whatever.h`
# include <objc-compat/objc-compat.h>   // objc-compat

#endif
