/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _Foundation_include_h__
#define _Foundation_include_h__

// How to tweak the following MulleFoundation #include
//    remove:          `mulle-sourcetree mark MulleFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleFoundation set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark MulleFoundation [no-]import`
//    toggle public:   `mulle-sourcetree mark MulleFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleFoundation no-os-<osname>`
# include <MulleFoundation/MulleFoundation.h>   // MulleFoundation

// How to tweak the following mulle-objc-compat #include
//    remove:          `mulle-sourcetree mark mulle-objc-compat no-header`
//    rename:          `mulle-sourcetree mark mulle-objc-compat set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark mulle-objc-compat [no-]import`
//    toggle public:   `mulle-sourcetree mark mulle-objc-compat [no-]public`
//    toggle optional: `mulle-sourcetree mark mulle-objc-compat [no-]require`
//    remove for os:   `mulle-sourcetree mark mulle-objc-compat no-os-<osname>`
# include <mulle-objc-compat/mulle-objc-compat.h>   // mulle-objc-compat

// How to tweak the following objc-compat #include
//    remove:          `mulle-sourcetree mark objc-compat no-header`
//    rename:          `mulle-sourcetree mark objc-compat set include whatever.h`
//    toggle #import:  `mulle-sourcetree mark objc-compat [no-]import`
//    toggle public:   `mulle-sourcetree mark objc-compat [no-]public`
//    toggle optional: `mulle-sourcetree mark objc-compat [no-]require`
//    remove for os:   `mulle-sourcetree mark objc-compat no-os-<osname>`
# include <objc-compat/objc-compat.h>   // objc-compat

#endif
